sudo: false

language: php

php:
  - 7.1


cache:
  directories:
    - vendor
    - $HOME/.composer/cache

install:
  - composer self-update && composer --version
  - composer install

script:
  - php vendor/bin/codecept run
